# Generated by Django 5.1.3 on 2025-05-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conducteur',
            name='date_souscription_assurance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conducteur',
            name='date_souscription_droit_taxi',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conducteur',
            name='validite_assurance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
